fruitproject/fruitproject/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fruitproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/', include('register.urls',namespace="register")),
    url(r'^sysadmin/', include('sysadmin.urls',namespace="sysadmin")),
)

fruitproject/register/urls.py
from django.conf.urls import patterns, url

from register  import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^list$', views.list, name='list'),
    url(r'^addUser/$', views.addUser, name='addUser'),

)

fruitproject/sysadmin/urls.py
from django.conf.urls import patterns, url

from sysadmin  import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^addArticle/$', views.addArticle, name='addArticle'),
    url(r'^deleteArticle/$', views.delArticle, name='delArticle'),
    url(r'^uploadPhoto/$', views.uploadPhoto, name='uploadPhoto'),
    url(r'^(\d+)/$', views.readArticle, name='readArticle'),
)

fruitproject/register/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
	nickname = models.CharField(max_length=30)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=30)

	def __unicode__(self):
		return "%s, %s, %s" % (self.nickname, self.email, self.password)

fruitproject/sysadmin/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=40)
	pub_date = models.DateTimeField('date published')
	article_id = models.IntegerField(default=0)
	summary = models.CharField(max_length=200)
	content = models.CharField(max_length=5000)
	author = models.CharField(max_length=30)


class uploadPhoto(models.Model):
	picture_id = models.IntegerField(default=0)
	#photo = models.ImageField(upload_to='/photos')	

fruitproject/register/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render_to_response
from register.models import Register

import MySQLdb

# "-id" : Descending id order
def index(request):
    return render_to_response('register/index.html')
    

def list(request):
    latest_register_list = Register.objects.order_by('-id')[:25]
    template = loader.get_template('register/list.html')
    context = RequestContext(request, {
        'latest_register_list': latest_register_list,
    })
    return HttpResponse(template.render(context))


def addUser(request):
	from django.db import connection
	name = request.GET['nickname']
	email = 'test@email.com'
	pwd = request.GET['password']
	db =  MySQLdb.connect(user='root', db='fruitdata', passwd='ssinsky')
	cursor = connection.cursor()
	cursor.execute("INSERT INTO register_register (nickname, email, password) values (%s, %s, %s)", [name, email, pwd])
	db.close()


	info = '<h2>SUCCESS! You have added:</h2>' + '<br>' + name + '<br>' + email + '<br>' + pwd

	return HttpResponse(info)

fruitproject/sysadmin/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render_to_response, render, redirect
from sysadmin.models import Article
from .upload_form import UploadImageForm
from django.views.decorators.csrf import csrf_exempt
from .models import uploadPhoto
from .handle_uploaded_file import handle_uploaded_file


import MySQLdb

def index(request):
    latest_article_list = Article.objects.order_by('-id')[:30]
    for index, article in enumerate(latest_article_list):
        article.index = index + 1;
    template = loader.get_template('article/index.html')
    context = RequestContext(request, {
        'latest_article_list': latest_article_list,
    })
    return HttpResponse(template.render(context))

def addArticle(request):
    from django.db import connection
    article_id = request.GET['article-id']
    author = request.GET['author']
    title = request.GET['title']
    time = request.GET['time']
    summary = request.GET['summary']
    content = request.GET['content']
    db =  MySQLdb.connect(user='root', db='fruitdata', passwd='ssinsky')
    cursor = connection.cursor()
    cursor.execute("INSERT INTO sysadmin_article (title, pub_date, article_id,summary,content,author) values (%s, %s, %s, %s, %s, %s)", [title, time, article_id,summary,content,author])
    db.close()
    return redirect('/sysadmin')

def delArticle(request):
    from django.db import connection
    delIds = request.GET['delete-ids']
    delIdsList = delIds.split(',')
    db =  MySQLdb.connect(user='root', db='fruitdata', passwd='ssinsky')
    cursor = connection.cursor()

    for delId in delIdsList:
        cursor.execute("DELETE FROM sysadmin_article WHERE  id = %s",delId)
    return redirect('/sysadmin')

def readArticle(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'article/article.html', {'article': article})  

@csrf_exempt
def uploadPhoto(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['photo'])
            return HttpResponse('ok')
    else:
        form = UploadImageForm()
    return render_to_response('photo/upload.html', {'form': form})

fruitproject/register/templates/register/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'register/css/index.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'register/css/main.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'register/css/register-log.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'register/css/plug/dialog.css' %}" />

<div class="nav-top-wrapper">
	<div id="nav-top">
		<div class="left">欢迎来到【果百乐】！
			<span class="favor"><i></i>加入收藏</span>
			<span class="mobile-link"><i></i>手机访问</span>
			<span class="chat"><i></i></span>
		</div>
		<div class="right">您好！<span id="login" class="red">[ 请登录 ]</span><span class="red">[ 免费注册 ]</span><span class="shopping-car"><i></i>我的购物车[ <span>10</span> ]</span><a href="">帮助中心</a></div>
	</div>
</div>

<div class="head clearfix">
	<div id="logo"><img src="{% static 'register/images/logo.png' %}"></div>
	<div id="position">我在[杭州]</div>
	<div class="search">
		<div class="search-bar">
			<i class="search-icon"></i>
			<input type="text" class="search-input">
			<button type="submit">搜索</button>
		</div>
		<div class="hot-word"><span class="word">热门搜索:</span><span>奇异果 苹果 芒果</span></div>
	</div>
	<div class="share">
		<span>分享到</span>
		<i class="zone"></i>
		<i class="weibo"></i>
		<i class="weixin"></i>
		<i class="add-share"></i>
	</div>
</div>
<div class="nav">
	<ul>
		<li class="current"><a href="">首页</a></li>
		<li><a href="">在线商城</a></li>
		<li><a href="">健康果语</a></li>
		<li><a href="">联系我们</a></li>
	</ul>
</div>
<div class="crumb"><i class="p-icon"></i>您当前的位置：<a href="">首页</a> > <a href="">注册账号</a></div>
<!--content start-->
<div class="content reg-log">
	<div class="register">
		<div class="welcome"><img src="{% static 'register/images/add.png' %}"> 欢迎加入百果乐</div>
		<div class="reg-form">
			<form id="register-form" action="addUser" method="get">
				<ul>
					<li>
						<label>账号</label>
						<div>
							<input name="nickname" type="text">
							<span class="tip">注册成功后不可修改，请慎重！</span>
					    </div>
					</li>
					<li>
						<label>密码</label>
						<div>
							<input name="password" type="password">
							<span class="tip">字母、数字或者英文符号，最短6位，区分大小写</span>
					    </div>
					</li>
					<li>
						<label>确认密码</label>
						<div>
							<input name="password-confirm" type="password">
							<span class="tip">请再次输入密码</span>
					    </div>
					</li>
					<li>
						<label>验证码</label>
						<div class="w347">
							<input name="vcode" class="vcode-input" type="text">
							<div class="vcode"><img src="{% static 'register/images/vcode.png' %}"><a class="blue" href="">换一张</a></div>
					    </div>
					</li>
					<li>
						<div class="margin-label"><input type="checkbox">我同意并遵守<span class="blue">《果百乐用户协议》</span></div>
					</li>
					<li>
						<div class="margin-label"><span id="register-submit" class="btn">立即注册</span></div>
					</li>
				</ul>
			</form>
		</div>
		<div class="other">
			<div><i class="arrow"></i>我已有账号，<a class="other-login" href="">登录</a></div>
			<div><i class="arrow"></i><a class="find-pwd" href="">我忘记密码了？</a></div>
		</div>
	</div>
</div>
<!--content end-->
<script type="text/javascript" src="{% static 'register/js/jquery-1.11.1.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/plugs/jquery.Dialog.js' %}"></script>
<script type="text/javascript">
	$(function(){
		$('#login').click(function(){
			new Dialog({
				width:398,
				height:316,
				title:'会员登录',
				skinClassName:'login-dialog',
				content:'<div><div class="field"><span class="icon-account"></span><input type="text" class="text" placeholder="请输入账号"></div><div class="field"><span class="icon-key"></span><input type="password" class="text" placeholder="请输入密码"></div></div><div class="entries"><span><a href="">忘记密码？</a></span></div><button class="login-btn">登录</button>',
				button4login: '登录',
				loginFn: function(){

				}
			});
		});

		$('#register-submit').click(function(){
			$('#register-form').submit();
		});

	});
</script>

fruitproject/register/templates/register/list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}" />
<h2>Nickname:Email</h2>
{% if latest_register_list %}
    <ul>
    {% for register in latest_register_list %}
        <li><a href="/register/{{ register.id }}/">{{ register.nickname }}</a>:{{ register.email }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No register are available.</p>
{% endif %}

fruitproject/sysadmin/templates/article/article.html
<h1>{{article.title}}</h1>
<div><span>{{article.author}}</span>    <span>{{article.pub_date}}</span></div>
<p>{{article.content}}</p>

fruitproject/sysadmin/templates/article/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'article/css/style.css' %}" />



<div class="header clearfix">
	<div class="logo-wrapper" id="logo"><img  src="{% static 'article/images/logo.png' %}"><span>系统管理平台</span></div>
</div>
<div class="nav">
	<ul class="clearfix">
		<li><a href="">图库管理</a></li>
		<li class="current"><a href="">文库管理</a></li>
		<li><a href="">图库管理3</a></li>
		<li><a href="">图库管理4</a></li>
	</ul>
</div>
<!--content start-->
<div class="content">
	<div class="article">
		<div class="vertical-nav">
			<ul>
				<li class="current"><a href="">文章管理</a></li>
				<li><a href="">百果说</a></li>
				<li><a href="">今日关注</a></li>
				<li><a href="">养生果语</a></li>
				<li><a href="">热门精选</a></li>
				<li><a href="">发现好果</a></li>
			</ul>
		</div>
		<div class="main-content clearfix">
			<div class="list-article">
				<h3>文章列表<span id="delete-article" class="delete-article">[<span>删除选中</span>]</span></h3>
				<div class="table-article">
					<div class="table-header">
						<span class="select">选择</span>
						<span class="article-index">序号</span>
						<span class="article-id">ID</span>
						<span class="title">文章标题</span>
						<span class="author">作者</span>
						<span class="date">日期</span>
					</div>

					<ul class="table-body">						
						{% if latest_article_list %}
					    {% for article in latest_article_list %}
					        <li>
					        	<span class="select"><input type="checkbox" id="{{ article.id }}"/></span>
					        	<a target="_blank" href="{% url 'sysadmin:readArticle' article.id %}">
					        		<span class="article-index">{{ article.index }}</span>
					        		<span class="article-id">{{ article.article_id }}</span>
					        		<span class="title">{{ article.title }}</span>
									<span class="author">{{ article.author }}</span>
									<span class="date">{{ article.pub_date|date:"Y-m-d" }}</span>
								</a>	
					        </li>
					    {% endfor %}
						{% else %}
						    <li>No article are available.</lis>
						{% endif %}
					</ul>	
				</div>
			</div>
			<div class="add-article">
				<h3>上传新文章：</h3>
				<form action="addArticle" method="get">
					<ul>
						<li>	
							<div class="form-item fl" >
								<label>文章ID</label>
								<div class="articleid-input">
									<input name="article-id" type="text">
									<span class="tip"></span>
							    </div>
							</div>
						    <div class="form-item fr">
						    	<label>作者</label>
								<div class="author-input">
									<input name="author" type="text">
									<span class="tip"></span>
							    </div>
						    </div>
						</li>
						<li>
							<label>标题</label>
							<div class="title-input">
								<input name="title" type="text">
								<span class="tip"></span>
						    </div>
						</li>
						<li>
							<label>日期</label>
							<div class="date-input">
								<input name="time" type="text">
								<span class="tip"></span>
						    </div>
						</li>
						<li>
							<label>摘要</label>
							<div>
								<textarea class="summary" name="summary"></textarea>
								<span class="tip"></span>
						    </div>
						</li>
						<li class="content-textarea">
							<label>正文</label>
							<div>
								<textarea class="form-content" name="content"></textarea>
								<span class="tip"></span>
						    </div>
						</li>
						<li>
							<div class="margin-label"><input type="submit" value="保存"></div>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
<form id="deleteForm" action="deleteArticle" method="get" class="hide">
	<input id="delete-ids" name="delete-ids" type="text">
</form>
<!--content end-->
<script type="text/javascript" src="{% static 'article/js/jquery-1.11.1.js' %}"></script>
<script>
	$(function(){
		$('#delete-article').click(function(){
			var checkboxes = $('.table-body').find('input[type="checkbox"]'),
			ids = [];
			checkboxes.each(function(){
				if(this.checked){
					ids.push(this.id);
				}
				$('#delete-ids').val(ids);
				$('#deleteForm').submit();
			});

		});
	});
</script>

fruitproject/sysadmin/templates/photo/upload.html
<form enctype="multipart/form-data" method="post" action="">
	<input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}"/>
    <ul>
    	{{ form.as_ul }}
    	<li><input type="submit" value="Submit" /></li>
    </ul>
    
</form>